# Generated by Django 4.2.1 on 2023-12-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("photo", models.URLField(verbose_name="foto")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
            ],
            options={
                "verbose_name": "palestrante",
                "verbose_name_plural": "palestrantes",
            },
        ),
        migrations.CreateModel(
            name="ContactSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("E", "Email"), ("P", "Telefone")],
                        max_length=1,
                        verbose_name="tipo",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="valor")),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.speaker",
                        verbose_name="palestrante",
                    ),
                ),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
            },
        ),
    ]
