# Generated by Django 4.2.1 on 2023-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactSpeaker",
        ),
    ]
