# Generated by Django 4.2.1 on 2023-12-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_contact_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
